/**
 * detail pl inv 2026_00031.xlsx - the only multi-width supplier document we hold.
 *
 * GENERATED by scripts/gen-detail-pl.py. Do not hand-edit; the generator is committed
 * next to this file precisely so it can be re-run (unlike archTallyFixtures.ts, whose
 * generator was lost with a scratchpad).
 *
 * WHY IT MATTERS. Until this was read, archTally.ts asserted that no real document
 * carries a per-bundle matrix. It does: 14 bundles, one thickness and ONE length each,
 * but 11 to 22 distinct WIDTHS across 31 populated columns from 100mm to 400mm in even
 * 10mm steps.
 *
 * RECONCILED 14/14 on both axes against the document's own totals row:
 *   pieces  - each bundle's width counts sum to its stated t_pcs, exactly
 *   volume  - sum(pieces x width_mm x thick_mm x len_mm) / 1e9 matches stated t_vol,
 *             worst residual 0.0005 m3
 *   totals  - 1901 pieces, 31.9613 m3, 14 bundles
 *
 * ⚠️ NOT IN DEMO_DOCS, DELIBERATELY. This document is metric (2400-4500mm), so through
 * rowLabel() its lengths render as 7.874' / 8.858' / 9.843' - correct and unreadable.
 * Adding it to the demo rotation would degrade the working length view on roughly a
 * third of ARCH lots. It feeds tests and the width view only.
 *
 * ⚠️ Widths are stored in MILLIMETRES with matrix.widthUnit = 'mm'. Converting the even
 * 10mm steps to inches yields 3.937 / 4.331 / 4.724, which stop round-tripping the
 * moment any consumer rounds them.
 *
 * The document names a sales contract (S00189 (CWP/6028/08/2025)), not a PO, so `po` is null. `lot` is null on
 * every bundle: the per-bundle key here is t_bdleno (WTR003/A1565...), while t_lotno is
 * document-level (WTR003) and shared by all 14 - keying on it would make bundlesForLot()
 * return the whole document for any lot.
 */

import type { TallyPayload } from '@/lib/archTally';

export const TALLY_DETAIL_PL: TallyPayload = {
  schema: 'mgsl.tally.v1',
  po: null,
  container: "CAAU9944443",
  bundles: [
  {
    bundleNo: "WTR003/A1565",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.858,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 290, 330, 340],
      rows: [{ lengthFt: 8.858, pieces: { "120": 1, "130": 3, "140": 4, "150": 10, "160": 9, "170": 12, "180": 7, "190": 9, "200": 6, "210": 8, "220": 7, "230": 3, "240": 5, "250": 1, "260": 2, "270": 3, "290": 1, "330": 1, "340": 1 } }],
    },
    totals: { pieces: 93, boardFeet: null, volumeM3: 1.206 },
  },
  {
    bundleNo: "WTR003/A1566",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 7.874,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 270, 300, 340],
      rows: [{ lengthFt: 7.874, pieces: { "130": 4, "140": 10, "150": 16, "160": 7, "170": 9, "180": 13, "190": 8, "200": 6, "210": 4, "220": 8, "230": 3, "240": 1, "250": 1, "270": 1, "300": 2, "340": 1 } }],
    },
    totals: { pieces: 94, boardFeet: null, volumeM3: 1.021 },
  },
  {
    bundleNo: "WTR003/A1825",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 11.811,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 310, 320, 340, 360, 370, 380],
      rows: [{ lengthFt: 11.811, pieces: { "140": 1, "150": 4, "160": 18, "170": 15, "180": 24, "190": 17, "200": 17, "210": 15, "220": 22, "230": 5, "240": 14, "250": 9, "260": 11, "270": 1, "280": 8, "290": 1, "310": 2, "320": 1, "340": 1, "360": 1, "370": 1, "380": 3 } }],
    },
    totals: { pieces: 191, boardFeet: null, volumeM3: 3.6612 },
  },
  {
    bundleNo: "WTR003/A1826",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 13.78,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 110, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 330],
      rows: [{ lengthFt: 13.78, pieces: { "100": 1, "110": 1, "150": 9, "160": 6, "170": 15, "180": 12, "190": 15, "200": 12, "210": 7, "220": 13, "230": 32, "240": 10, "250": 15, "260": 5, "270": 10, "280": 4, "290": 7, "300": 3, "310": 4, "330": 1 } }],
    },
    totals: { pieces: 182, boardFeet: null, volumeM3: 4.194 },
  },
  {
    bundleNo: "WTR003/A1830",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 9.843,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [130, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320],
      rows: [{ lengthFt: 9.843, pieces: { "130": 2, "150": 6, "160": 16, "170": 11, "180": 17, "190": 17, "200": 20, "210": 13, "220": 15, "230": 16, "240": 12, "250": 16, "260": 2, "270": 10, "280": 6, "290": 7, "300": 4, "310": 1, "320": 2 } }],
    },
    totals: { pieces: 193, boardFeet: null, volumeM3: 3.116 },
  },
  {
    bundleNo: "WTR003/A1831",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 9.843,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320],
      rows: [{ lengthFt: 9.843, pieces: { "150": 2, "160": 16, "170": 29, "180": 7, "190": 15, "200": 19, "210": 13, "220": 16, "230": 19, "240": 10, "250": 13, "260": 10, "270": 5, "280": 6, "290": 1, "300": 4, "310": 2, "320": 4 } }],
    },
    totals: { pieces: 191, boardFeet: null, volumeM3: 3.0742 },
  },
  {
    bundleNo: "WTR003/A1841",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 14.764,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 310, 320],
      rows: [{ lengthFt: 14.764, pieces: { "150": 15, "160": 7, "170": 17, "180": 25, "190": 16, "200": 17, "210": 9, "220": 22, "230": 19, "240": 11, "250": 12, "260": 5, "270": 7, "280": 2, "290": 5, "310": 3, "320": 1 } }],
    },
    totals: { pieces: 193, boardFeet: null, volumeM3: 4.544 },
  },
  {
    bundleNo: "WTR003/A1844",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 12.795,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 310, 340],
      rows: [{ lengthFt: 12.795, pieces: { "130": 1, "140": 3, "150": 8, "160": 16, "170": 17, "180": 33, "190": 27, "200": 28, "210": 11, "220": 13, "230": 10, "240": 8, "250": 12, "260": 4, "270": 7, "280": 4, "290": 1, "310": 1, "340": 2 } }],
    },
    totals: { pieces: 206, boardFeet: null, volumeM3: 4.055 },
  },
  {
    bundleNo: "WTR003/A1846",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 7.874,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 320, 330, 340, 360],
      rows: [{ lengthFt: 7.874, pieces: { "150": 6, "160": 20, "170": 20, "180": 27, "190": 31, "200": 18, "210": 21, "220": 13, "230": 10, "240": 6, "250": 8, "260": 6, "270": 3, "280": 6, "290": 4, "300": 1, "320": 1, "330": 1, "340": 1, "360": 2 } }],
    },
    totals: { pieces: 205, boardFeet: null, volumeM3: 2.525 },
  },
  {
    bundleNo: "WTR003/A1847",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 10.827,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 270, 280, 290, 300, 310, 370],
      rows: [{ lengthFt: 10.827, pieces: { "140": 2, "150": 2, "160": 10, "170": 10, "180": 10, "190": 6, "200": 8, "210": 8, "220": 6, "230": 6, "240": 3, "250": 7, "270": 3, "280": 4, "290": 1, "300": 1, "310": 2, "370": 1 } }],
    },
    totals: { pieces: 90, boardFeet: null, volumeM3: 1.5493 },
  },
  {
    bundleNo: "WTR003/A2645",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 7.874,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 110, 120, 130, 140, 150, 160, 170, 180, 210, 230, 240],
      rows: [{ lengthFt: 7.874, pieces: { "100": 16, "110": 7, "120": 16, "130": 18, "140": 25, "150": 8, "160": 5, "170": 5, "180": 2, "210": 1, "230": 1, "240": 1 } }],
    },
    totals: { pieces: 105, boardFeet: null, volumeM3: 0.8412 },
  },
  {
    bundleNo: "WTR003/A2683",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.858,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 260, 270, 290, 300],
      rows: [{ lengthFt: 8.858, pieces: { "100": 1, "120": 3, "130": 3, "140": 3, "150": 4, "160": 6, "170": 3, "180": 8, "190": 3, "200": 2, "210": 16, "220": 2, "230": 2, "240": 2, "260": 1, "270": 2, "290": 1, "300": 3 } }],
    },
    totals: { pieces: 65, boardFeet: null, volumeM3: 0.8424 },
  },
  {
    bundleNo: "WTR003/A3535",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 9.843,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [120, 130, 140, 150, 160, 180, 190, 200, 210, 220, 230, 240, 250, 260],
      rows: [{ lengthFt: 9.843, pieces: { "120": 1, "130": 1, "140": 5, "150": 4, "160": 5, "180": 5, "190": 3, "200": 2, "210": 2, "220": 1, "230": 2, "240": 5, "250": 1, "260": 2 } }],
    },
    totals: { pieces: 39, boardFeet: null, volumeM3: 0.547 },
  },
  {
    bundleNo: "WTR003/A3546",
    lot: null,
    species: "SAPELI KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "25.00mm", inches: 0.984 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 9.843,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [120, 140, 150, 160, 170, 180, 190, 200, 220, 230, 240],
      rows: [{ lengthFt: 9.843, pieces: { "120": 2, "140": 3, "150": 4, "160": 4, "170": 1, "180": 3, "190": 3, "200": 19, "220": 4, "230": 4, "240": 7 } }],
    },
    totals: { pieces: 54, boardFeet: null, volumeM3: 0.785 },
  },
  ],
  provenance: {
    sourceFile: 'detail pl inv 2026_00031.xlsx',
    parsedAt: null,
    skill: 'gen-detail-pl.py@1 (stdlib xlsx read, reconciled)',
    reviewedBy: null,
  },
};

/** The document's own totals row, for tests to assert against. */
export const DETAIL_PL_TOTALS = { bundles: 14, pieces: 1901, volumeM3: 31.9613 } as const;
