/**
 * pl inv 05513.xlsx - a real supplier document with TWO-AXIS bundles.
 *
 * 🔴 TEST-ONLY. DO NOT ADD THIS TO ALL_DEMO_DOCS.
 *
 * This document exists here to HARDEN THE CODE, not to decorate the screen. It is the
 * gnarliest tally we hold, which makes it the best stress case for the grid reducer and
 * the worst thing to put in front of a trader: every figure in it belongs to a shipment
 * that has nothing to do with whichever lot the demo would attach it to.
 *
 * The demo rotation already carries ONE such document (archTallyZebrano.ts), labelled
 * on screen as a sample, which is enough to answer the client's question about the
 * FORMAT. A second one would double the amount of not-his-data on his screen and answer
 * nothing he asked. Decided 2026-09-10; the reasoning is in the todo-list, question 9.
 *
 * Use it in tests. Assert against it freely. Do not import it into archTallyFixtures.ts.
 *
 * GENERATED by scripts/gen-zebrano.mjs. Do not hand-edit; the generator is committed
 * next to this file precisely so it can be re-run (unlike archTallyFixtures.ts, whose
 * generator was lost with a scratchpad). The source xlsx lives under `docs/`, which is
 * never committed - see the generator's header for the path and the exact command.
 *
 * WHY IT MATTERS. Every document before this one had ONE length per bundle, so the
 * tally view could be two 1-D tables (lengths across bundles, widths within a bundle).
 * Here 10 of 15 bundles span SEVERAL lengths, each with its own width spread:
 * 10 has 8 lengths, 12 has 5 lengths, 13 has 6 lengths, 5 has 2 lengths, 6 has 2 lengths, 8 has 2 lengths, ....
 * That is the shape Marc-Antoine's Feedback 3 mockup draws as a grid, and it is what
 * `toLengthWidthGrid()` in archTally.ts renders.
 *
 * RECONCILED on emit, and the generator refuses to write if it cannot:
 *   pieces - every row's width cells sum to that row's own printed t_pcs, exactly
 *   totals - 1398 pieces across 15 bundles
 *
 * ⚠️ LENGTHS ARE METRIC, on a 50mm grid (2250, 2300, 2350mm...). They print as
 * millimetres only because archTallyLength.ts's METRIC_STEP_MM is 50; at the old 100mm
 * step five of bundle 11's nine lengths rendered as 7.382' / 7.71' / 8.038' / 8.366' /
 * 8.694'. See that file's measured soundness table before touching the step.
 *
 * ⚠️ `lot` is null on every bundle. The per-bundle key here is the supplier's own
 * t_bdleno ('11', '12-A', '16-B'), which matches no NetSuite inventory number - the
 * open question recorded in the todo-list as "14 bundles sur une ligne de PO". Keying
 * on the document-level t_lotno instead would make bundlesForLot() return the whole
 * document for any lot.
 */

import type { TallyPayload } from '@/lib/archTally';

export const TALLY_ZEBRANO05513: TallyPayload = {
  schema: 'mgsl.tally.v1',
  po: null,
  container: "HAMU4239913",
  bundles: [
  {
    bundleNo: "1",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.53,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 260, 270, 280, 290, 310, 340],
      rows: [
        { lengthFt: 8.53, pieces: { '70': 1, '80': 2, '90': 2, '100': 2, '110': 3, '120': 7, '130': 7, '140': 6, '150': 5, '160': 7, '170': 11, '180': 5, '190': 8, '200': 10, '210': 9, '220': 3, '230': 3, '240': 4, '260': 1, '270': 1, '280': 2, '290': 4, '310': 3, '340': 1 } }, // 2600mm, t_pcs=107
      ],
    },
    totals: { pieces: 107, boardFeet: null, volumeM3: 2.5233 },
  },
  {
    bundleNo: "10",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 80, 100, 110, 120, 150, 160, 170, 190, 200, 220, 240, 250, 270],
      rows: [
        { lengthFt: 6.89, pieces: { '80': 1, '160': 1, '200': 1 } }, // 2100mm, t_pcs=3
        { lengthFt: 7.054, pieces: { '110': 1, '150': 1, '170': 1 } }, // 2150mm, t_pcs=3
        { lengthFt: 7.218, pieces: { '120': 1, '150': 1 } }, // 2200mm, t_pcs=2
        { lengthFt: 7.382, pieces: { '100': 1, '110': 1, '190': 1, '200': 1 } }, // 2250mm, t_pcs=4
        { lengthFt: 7.546, pieces: { '70': 1, '80': 1, '170': 1, '240': 1, '250': 1 } }, // 2300mm, t_pcs=5
        { lengthFt: 7.874, pieces: { '150': 1, '160': 1 } }, // 2400mm, t_pcs=2
        { lengthFt: 8.038, pieces: { '120': 1, '150': 1 } }, // 2450mm, t_pcs=2
        { lengthFt: 8.366, pieces: { '170': 1, '220': 3, '270': 1 } }, // 2550mm, t_pcs=5
      ],
    },
    totals: { pieces: 26, boardFeet: null, volumeM3: 0.4937 },
  },
  {
    bundleNo: "12",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 280, 290, 330, 340, 350],
      rows: [
        { lengthFt: 8.038, pieces: { '100': 1, '150': 1, '190': 1, '240': 1 } }, // 2450mm, t_pcs=4
        { lengthFt: 8.202, pieces: { '100': 1, '110': 3, '130': 1, '140': 2, '160': 1, '190': 1, '200': 2, '230': 2, '260': 1, '330': 1 } }, // 2500mm, t_pcs=15
        { lengthFt: 8.53, pieces: { '100': 2, '190': 1, '200': 1, '230': 2, '260': 1, '290': 2 } }, // 2600mm, t_pcs=9
        { lengthFt: 8.694, pieces: { '70': 4, '80': 4, '90': 5, '100': 2, '110': 3, '120': 8, '130': 6, '140': 3, '150': 4, '160': 6, '170': 5, '180': 4, '190': 4, '200': 2, '210': 2, '220': 4, '230': 2, '250': 3, '260': 1, '340': 1 } }, // 2650mm, t_pcs=73
        { lengthFt: 8.858, pieces: { '90': 1, '100': 1, '140': 1, '150': 1, '160': 2, '170': 2, '180': 2, '190': 3, '200': 1, '230': 1, '250': 1, '280': 1, '330': 1, '350': 1 } }, // 2700mm, t_pcs=19
      ],
    },
    totals: { pieces: 120, boardFeet: null, volumeM3: 2.6376 },
  },
  {
    bundleNo: "13",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 400],
      rows: [
        { lengthFt: 8.038, pieces: { '100': 7, '110': 4, '120': 5, '130': 2, '140': 2, '150': 3, '160': 3, '170': 1, '180': 2, '190': 1, '200': 3, '210': 1, '220': 1, '250': 1, '280': 1 } }, // 2450mm, t_pcs=37
        { lengthFt: 8.202, pieces: { '100': 1, '110': 2, '120': 1, '130': 2, '180': 1, '200': 1, '210': 4, '240': 2, '260': 1, '270': 1 } }, // 2500mm, t_pcs=16
        { lengthFt: 8.366, pieces: { '130': 1, '150': 1, '190': 1, '200': 1, '210': 2, '220': 1, '280': 1, '300': 1, '400': 1 } }, // 2550mm, t_pcs=10
        { lengthFt: 8.694, pieces: { '110': 1, '150': 2, '180': 1, '190': 1 } }, // 2650mm, t_pcs=5
        { lengthFt: 8.858, pieces: { '270': 1, '290': 1 } }, // 2700mm, t_pcs=2
        { lengthFt: 9.022, pieces: { '80': 1, '90': 1, '100': 2, '120': 1, '130': 3, '140': 5, '150': 3, '160': 2, '170': 6, '180': 4, '190': 4, '200': 2, '210': 4, '220': 3, '230': 4, '250': 1, '290': 1 } }, // 2750mm, t_pcs=47
      ],
    },
    totals: { pieces: 117, boardFeet: null, volumeM3: 2.6409 },
  },
  {
    bundleNo: "2",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.53,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320],
      rows: [
        { lengthFt: 8.53, pieces: { '100': 3, '110': 2, '120': 2, '130': 2, '140': 1, '150': 7, '160': 3, '170': 5, '180': 6, '190': 4, '200': 4, '210': 12, '220': 7, '230': 9, '240': 8, '250': 8, '260': 9, '270': 1, '280': 1, '290': 1, '300': 1, '310': 1, '320': 1 } }, // 2600mm, t_pcs=98
      ],
    },
    totals: { pieces: 98, boardFeet: null, volumeM3: 2.6442 },
  },
  {
    bundleNo: "3",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.53,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 380, 410, 420],
      rows: [
        { lengthFt: 8.53, pieces: { '70': 1, '90': 8, '100': 9, '110': 3, '120': 2, '130': 3, '140': 8, '150': 7, '160': 8, '170': 9, '180': 3, '190': 8, '200': 2, '210': 2, '220': 3, '230': 6, '240': 3, '250': 2, '260': 2, '270': 3, '280': 4, '290': 2, '300': 1, '310': 1, '320': 1, '380': 1, '410': 1, '420': 2 } }, // 2600mm, t_pcs=105
      ],
    },
    totals: { pieces: 105, boardFeet: null, volumeM3: 2.5168 },
  },
  {
    bundleNo: "4",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.202,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [60, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 300, 310, 330, 360, 380, 410, 440],
      rows: [
        { lengthFt: 8.202, pieces: { '60': 1, '80': 1, '90': 2, '100': 3, '110': 5, '120': 8, '130': 5, '140': 5, '150': 6, '160': 6, '170': 2, '180': 6, '190': 7, '200': 6, '210': 3, '220': 5, '230': 5, '240': 3, '250': 6, '260': 5, '270': 2, '280': 1, '300': 2, '310': 1, '330': 1, '360': 1, '380': 1, '410': 1, '440': 3 } }, // 2500mm, t_pcs=103
      ],
    },
    totals: { pieces: 103, boardFeet: null, volumeM3: 2.5279 },
  },
  {
    bundleNo: "5",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 290, 300, 320, 330, 340, 380],
      rows: [
        { lengthFt: 8.53, pieces: { '90': 1, '100': 2, '110': 4, '120': 4, '130': 3, '140': 4, '150': 6, '160': 10, '170': 8, '180': 8, '190': 11, '200': 7, '210': 6, '220': 5, '230': 4, '240': 4, '250': 4, '260': 1, '290': 1, '380': 1 } }, // 2600mm, t_pcs=94
        { lengthFt: 8.858, pieces: { '130': 1, '180': 1, '260': 1, '300': 1, '320': 1, '330': 1, '340': 1, '380': 1 } }, // 2700mm, t_pcs=8
      ],
    },
    totals: { pieces: 102, boardFeet: null, volumeM3: 2.5281 },
  },
  {
    bundleNo: "6",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 280, 290, 300, 320, 330, 340, 350, 360, 410, 450],
      rows: [
        { lengthFt: 8.858, pieces: { '60': 1, '70': 1, '90': 1, '110': 1, '130': 3, '140': 3, '150': 5, '160': 3, '170': 1, '180': 3, '190': 1, '210': 2, '220': 3, '230': 2, '240': 1, '250': 1, '290': 1, '300': 1, '320': 1, '330': 1, '340': 2, '360': 1 } }, // 2700mm, t_pcs=39
        { lengthFt: 9.186, pieces: { '80': 1, '90': 1, '100': 3, '110': 3, '120': 3, '130': 5, '140': 4, '150': 1, '160': 1, '170': 3, '180': 1, '200': 2, '210': 2, '220': 4, '230': 3, '240': 7, '250': 1, '260': 3, '280': 1, '290': 1, '300': 2, '320': 1, '350': 1, '410': 3, '450': 1 } }, // 2800mm, t_pcs=58
      ],
    },
    totals: { pieces: 97, boardFeet: null, volumeM3: 2.7024 },
  },
  {
    bundleNo: "7",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.858,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 310, 330, 340, 350, 370],
      rows: [
        { lengthFt: 8.858, pieces: { '90': 3, '100': 3, '110': 6, '120': 4, '130': 6, '140': 6, '150': 2, '160': 2, '170': 5, '180': 6, '190': 5, '200': 12, '210': 4, '220': 2, '230': 2, '240': 5, '250': 3, '260': 2, '270': 4, '280': 2, '290': 5, '310': 2, '330': 2, '340': 2, '350': 1, '370': 3 } }, // 2700mm, t_pcs=99
      ],
    },
    totals: { pieces: 99, boardFeet: null, volumeM3: 2.6936 },
  },
  {
    bundleNo: "8",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 290, 300, 320, 360, 390, 400, 410, 440, 450],
      rows: [
        { lengthFt: 8.202, pieces: { '90': 3, '100': 3, '120': 1, '130': 3, '140': 1, '150': 1, '160': 4, '170': 5, '180': 1, '200': 5, '210': 4, '220': 3, '250': 1, '260': 2, '270': 2, '290': 2, '300': 1, '360': 1, '390': 1, '440': 1, '450': 1 } }, // 2500mm, t_pcs=46
        { lengthFt: 8.53, pieces: { '90': 2, '100': 3, '110': 4, '120': 2, '130': 6, '140': 7, '150': 5, '160': 4, '180': 3, '190': 3, '200': 1, '210': 2, '220': 2, '230': 6, '240': 1, '250': 2, '270': 4, '290': 1, '300': 1, '320': 1, '400': 1, '410': 1 } }, // 2600mm, t_pcs=62
      ],
    },
    totals: { pieces: 108, boardFeet: null, volumeM3: 2.6536 },
  },
  {
    bundleNo: "9",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 340, 350, 360, 370, 400, 420],
      rows: [
        { lengthFt: 6.89, pieces: { '100': 1, '210': 1, '220': 1, '250': 1 } }, // 2100mm, t_pcs=4
        { lengthFt: 7.382, pieces: { '140': 1, '150': 1, '210': 2, '230': 2, '240': 1, '250': 1, '300': 1 } }, // 2250mm, t_pcs=9
        { lengthFt: 7.71, pieces: { '130': 1, '150': 3, '200': 1, '210': 1, '220': 1 } }, // 2350mm, t_pcs=7
        { lengthFt: 7.874, pieces: { '90': 1, '110': 1, '120': 1, '130': 1, '180': 1, '210': 2, '220': 1, '230': 1, '370': 1 } }, // 2400mm, t_pcs=10
        { lengthFt: 8.038, pieces: { '100': 1, '110': 1, '130': 1, '140': 2, '160': 1, '170': 1, '210': 2, '300': 1, '360': 1, '370': 1, '420': 1 } }, // 2450mm, t_pcs=13
        { lengthFt: 8.202, pieces: { '350': 1 } }, // 2500mm, t_pcs=1
        { lengthFt: 8.366, pieces: { '90': 1, '100': 2, '140': 1, '150': 3, '210': 2, '260': 1, '290': 1, '340': 1, '360': 1 } }, // 2550mm, t_pcs=13
        { lengthFt: 8.53, pieces: { '100': 1, '120': 1, '130': 1, '140': 1, '160': 2, '170': 2, '180': 3, '190': 2, '200': 1, '220': 2, '270': 1, '280': 1, '300': 1, '360': 1, '400': 1 } }, // 2600mm, t_pcs=21
        { lengthFt: 9.022, pieces: { '80': 1, '90': 1, '100': 1, '120': 2, '140': 2, '190': 1, '290': 1, '310': 1 } }, // 2750mm, t_pcs=10
      ],
    },
    totals: { pieces: 88, boardFeet: null, volumeM3: 2.1631 },
  },
  {
    bundleNo: "10-A",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 340, 350, 420],
      rows: [
        { lengthFt: 4.921, pieces: { '150': 1, '170': 1, '200': 1, '220': 1, '230': 1, '240': 1, '280': 1 } }, // 1500mm, t_pcs=7
        { lengthFt: 5.085, pieces: { '110': 1, '140': 1, '220': 1 } }, // 1550mm, t_pcs=3
        { lengthFt: 5.249, pieces: { '100': 1, '120': 1, '140': 2, '150': 1, '170': 3, '190': 1, '220': 2, '240': 1, '250': 1, '260': 1 } }, // 1600mm, t_pcs=14
        { lengthFt: 5.413, pieces: { '70': 1, '90': 1, '100': 1, '120': 2, '140': 1, '160': 2, '170': 1, '190': 1, '210': 1, '220': 1, '230': 1, '240': 1, '340': 1, '420': 1 } }, // 1650mm, t_pcs=16
        { lengthFt: 5.577, pieces: { '70': 1, '100': 1, '140': 1, '160': 1, '180': 1, '200': 1 } }, // 1700mm, t_pcs=6
        { lengthFt: 5.906, pieces: { '70': 1, '100': 1, '110': 1, '130': 3, '140': 1, '160': 1, '170': 1, '190': 1, '210': 2, '250': 1 } }, // 1800mm, t_pcs=13
        { lengthFt: 6.07, pieces: { '100': 1, '120': 1, '140': 1, '170': 1, '180': 2, '190': 2, '230': 1, '350': 1 } }, // 1850mm, t_pcs=10
        { lengthFt: 6.234, pieces: { '70': 1, '100': 1, '130': 2, '140': 1, '150': 1, '160': 1, '170': 2, '190': 1, '230': 1 } }, // 1900mm, t_pcs=11
        { lengthFt: 6.398, pieces: { '100': 1, '120': 1, '150': 1, '170': 1, '270': 1 } }, // 1950mm, t_pcs=5
        { lengthFt: 6.562, pieces: { '100': 1, '110': 1, '170': 1, '180': 1, '210': 1 } }, // 2000mm, t_pcs=5
        { lengthFt: 6.726, pieces: { '140': 1, '150': 1, '200': 1 } }, // 2050mm, t_pcs=3
      ],
    },
    totals: { pieces: 93, boardFeet: null, volumeM3: 1.3839 },
  },
  {
    bundleNo: "11",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 290, 300, 340, 400],
      rows: [
        { lengthFt: 3.117, pieces: { '290': 1 } }, // 950mm, t_pcs=1
        { lengthFt: 3.281, pieces: { '100': 1, '150': 1, '180': 1, '190': 2, '210': 2, '290': 1 } }, // 1000mm, t_pcs=8
        { lengthFt: 3.445, pieces: { '100': 1, '120': 1, '130': 1 } }, // 1050mm, t_pcs=3
        { lengthFt: 3.609, pieces: { '140': 1, '150': 1, '160': 1, '180': 2, '210': 2, '230': 1, '260': 1 } }, // 1100mm, t_pcs=9
        { lengthFt: 3.773, pieces: { '90': 1, '100': 1, '110': 1, '170': 1, '230': 1, '270': 1 } }, // 1150mm, t_pcs=6
        { lengthFt: 3.937, pieces: { '120': 1, '130': 1, '140': 1, '150': 1, '220': 1, '240': 2 } }, // 1200mm, t_pcs=7
        { lengthFt: 4.101, pieces: { '90': 2, '120': 1, '130': 2, '150': 1, '160': 1, '180': 2, '230': 2 } }, // 1250mm, t_pcs=11
        { lengthFt: 4.265, pieces: { '120': 1, '150': 1, '170': 1 } }, // 1300mm, t_pcs=3
        { lengthFt: 4.429, pieces: { '90': 2, '100': 3, '120': 1, '130': 1, '140': 1, '150': 2, '230': 1 } }, // 1350mm, t_pcs=11
        { lengthFt: 4.593, pieces: { '90': 1, '100': 2, '110': 1, '120': 4, '130': 2, '140': 1, '150': 1, '160': 1, '180': 1, '200': 4, '230': 1, '240': 1, '250': 1, '260': 1 } }, // 1400mm, t_pcs=22
        { lengthFt: 4.757, pieces: { '70': 1, '90': 1, '110': 2, '120': 1, '140': 1, '150': 2, '200': 1, '220': 1 } }, // 1450mm, t_pcs=10
        { lengthFt: 4.921, pieces: { '60': 2, '80': 1, '100': 2, '120': 1, '130': 1, '150': 2, '300': 1, '340': 1 } }, // 1500mm, t_pcs=11
        { lengthFt: 5.085, pieces: { '80': 1, '90': 1, '100': 3, '110': 1, '130': 1, '170': 1, '220': 1, '290': 1, '400': 1 } }, // 1550mm, t_pcs=11
        { lengthFt: 5.249, pieces: { '130': 1, '150': 1, '170': 1 } }, // 1600mm, t_pcs=3
        { lengthFt: 5.413, pieces: { '60': 1, '70': 2, '80': 2, '160': 1, '290': 1 } }, // 1650mm, t_pcs=7
      ],
    },
    totals: { pieces: 123, boardFeet: null, volumeM3: 1.2709 },
  },
  {
    bundleNo: "9-A",
    lot: null,
    species: "ZEBRANO KD",
    grade: "FAS",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [80, 100, 160, 170, 190, 200, 220, 250, 300],
      rows: [
        { lengthFt: 6.398, pieces: { '250': 1, '300': 1 } }, // 1950mm, t_pcs=2
        { lengthFt: 6.562, pieces: { '170': 2, '190': 2, '200': 1, '220': 1 } }, // 2000mm, t_pcs=6
        { lengthFt: 6.726, pieces: { '80': 1, '100': 1, '160': 1, '250': 1 } }, // 2050mm, t_pcs=4
      ],
    },
    totals: { pieces: 12, boardFeet: null, volumeM3: 0.2282 },
  },
  ],
  provenance: {
    sourceFile: "pl inv 05513.xlsx",
    parsedAt: null,
    skill: 'gen-zebrano.mjs@1 (SheetJS read, reconciled)',
    reviewedBy: null,
  },
};

/** The document's own figures, for tests to assert against. */
export const TALLY_ZEBRANO05513_TOTALS = { bundles: 15, pieces: 1398, multiLengthBundles: 10 } as const;
