/**
 * pl inv 01368.xlsx - a real supplier document with TWO-AXIS bundles.
 *
 * GENERATED by scripts/gen-zebrano.mjs. Do not hand-edit; the generator is committed
 * next to this file precisely so it can be re-run (unlike archTallyFixtures.ts, whose
 * generator was lost with a scratchpad). The source xlsx lives under `docs/`, which is
 * never committed - see the generator's header for the path and the exact command.
 *
 * WHY IT MATTERS. Every document before this one had ONE length per bundle, so the
 * tally view could be two 1-D tables (lengths across bundles, widths within a bundle).
 * Here 13 of 18 bundles span SEVERAL lengths, each with its own width spread:
 * 11 has 9 lengths, 12-B has 11 lengths, 13-B has 9 lengths, 14-C has 7 lengths, 15-B has 9 lengths, 16-B has 12 lengths, ....
 * That is the shape Marc-Antoine's Feedback 3 mockup draws as a grid, and it is what
 * `toLengthWidthGrid()` in archTally.ts renders.
 *
 * RECONCILED on emit, and the generator refuses to write if it cannot:
 *   pieces - every row's width cells sum to that row's own printed t_pcs, exactly
 *   totals - 1351 pieces across 18 bundles
 *
 * ⚠️ LENGTHS ARE METRIC, on a 50mm grid (2250, 2300, 2350mm...). They print as
 * millimetres only because archTallyLength.ts's METRIC_STEP_MM is 50; at the old 100mm
 * step five of bundle 11's nine lengths rendered as 7.382' / 7.71' / 8.038' / 8.366' /
 * 8.694'. See that file's measured soundness table before touching the step.
 *
 * ⚠️ `lot` is null on every bundle. The per-bundle key here is the supplier's own
 * t_bdleno ('11', '12-A', '16-B'), which matches no NetSuite inventory number - the
 * open question recorded in the todo-list as "14 bundles sur une ligne de PO". Keying
 * on the document-level t_lotno instead would make bundlesForLot() return the whole
 * document for any lot.
 */

import type { TallyPayload } from '@/lib/archTally';

export const TALLY_ZEBRANO: TallyPayload = {
  schema: 'mgsl.tally.v1',
  po: null,
  container: "MRSU3670682",
  bundles: [
  {
    bundleNo: "10",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.858,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280],
      rows: [
        { lengthFt: 8.858, pieces: { '100': 2, '110': 1, '120': 1, '130': 2, '140': 7, '150': 4, '160': 7, '170': 4, '180': 4, '190': 5, '200': 5, '210': 4, '220': 6, '230': 5, '240': 13, '250': 6, '260': 11, '270': 9, '280': 1 } }, // 2700mm, t_pcs=97
      ],
    },
    totals: { pieces: 97, boardFeet: null, volumeM3: 2.7326 },
  },
  {
    bundleNo: "11",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
      rows: [
        { lengthFt: 7.382, pieces: { '240': 1, '270': 1 } }, // 2250mm, t_pcs=2
        { lengthFt: 7.546, pieces: { '190': 1, '210': 1, '240': 2, '260': 1, '270': 2 } }, // 2300mm, t_pcs=7
        { lengthFt: 7.71, pieces: { '120': 1, '180': 1, '220': 1, '250': 1, '270': 1, '280': 1 } }, // 2350mm, t_pcs=6
        { lengthFt: 7.874, pieces: { '170': 1, '220': 1, '230': 1, '260': 1 } }, // 2400mm, t_pcs=4
        { lengthFt: 8.038, pieces: { '130': 1, '150': 1, '250': 1, '260': 2, '280': 1 } }, // 2450mm, t_pcs=6
        { lengthFt: 8.202, pieces: { '230': 1, '260': 1, '270': 1, '280': 1 } }, // 2500mm, t_pcs=4
        { lengthFt: 8.366, pieces: { '110': 1, '190': 1, '220': 1, '240': 2 } }, // 2550mm, t_pcs=5
        { lengthFt: 8.53, pieces: { '170': 1, '200': 1, '260': 1 } }, // 2600mm, t_pcs=3
        { lengthFt: 8.694, pieces: { '70': 2, '90': 1, '100': 2, '110': 2, '130': 6, '140': 2, '150': 7, '160': 4, '170': 3, '180': 4, '190': 6, '200': 1, '210': 2, '220': 4, '230': 6, '250': 4, '260': 1, '270': 3, '280': 2, '290': 1 } }, // 2650mm, t_pcs=63
      ],
    },
    totals: { pieces: 100, boardFeet: null, volumeM3: 2.5478 },
  },
  {
    bundleNo: "12-B",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280],
      rows: [
        { lengthFt: 6.89, pieces: { '230': 1, '240': 1 } }, // 2100mm, t_pcs=2
        { lengthFt: 7.054, pieces: { '200': 1, '270': 2 } }, // 2150mm, t_pcs=3
        { lengthFt: 7.218, pieces: { '130': 1, '200': 1, '220': 1, '230': 2 } }, // 2200mm, t_pcs=5
        { lengthFt: 7.382, pieces: { '210': 1, '230': 1, '250': 2, '260': 1 } }, // 2250mm, t_pcs=5
        { lengthFt: 7.546, pieces: { '150': 1, '170': 1, '190': 1, '220': 1, '230': 1, '260': 2 } }, // 2300mm, t_pcs=7
        { lengthFt: 7.71, pieces: { '110': 1, '140': 1, '190': 1, '200': 1, '220': 1, '230': 2, '240': 1, '260': 2, '270': 1 } }, // 2350mm, t_pcs=11
        { lengthFt: 7.874, pieces: { '190': 1, '210': 1, '250': 1, '280': 1 } }, // 2400mm, t_pcs=4
        { lengthFt: 8.038, pieces: { '100': 1, '110': 1, '140': 1, '160': 1, '180': 1, '230': 1, '240': 1, '260': 2, '280': 1 } }, // 2450mm, t_pcs=10
        { lengthFt: 8.202, pieces: { '120': 2, '130': 1, '170': 1, '200': 1, '210': 1, '240': 1 } }, // 2500mm, t_pcs=7
        { lengthFt: 8.694, pieces: { '100': 1, '110': 1, '160': 2 } }, // 2650mm, t_pcs=4
        { lengthFt: 9.35, pieces: { '90': 3, '150': 1, '160': 1, '230': 1, '240': 1 } }, // 2850mm, t_pcs=7
      ],
    },
    totals: { pieces: 65, boardFeet: null, volumeM3: 1.5426 },
  },
  {
    bundleNo: "13-B",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 110, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280],
      rows: [
        { lengthFt: 6.89, pieces: { '220': 1, '230': 1 } }, // 2100mm, t_pcs=2
        { lengthFt: 7.054, pieces: { '100': 1, '130': 1, '140': 1, '150': 1, '190': 1, '210': 1, '220': 4, '240': 1, '250': 1, '270': 1 } }, // 2150mm, t_pcs=13
        { lengthFt: 7.218, pieces: { '140': 2, '210': 1, '220': 2, '230': 2, '240': 1, '250': 1, '260': 1 } }, // 2200mm, t_pcs=10
        { lengthFt: 7.382, pieces: { '130': 1, '150': 1, '220': 2, '240': 1 } }, // 2250mm, t_pcs=5
        { lengthFt: 7.546, pieces: { '140': 1, '170': 1, '210': 1, '250': 1, '260': 2 } }, // 2300mm, t_pcs=6
        { lengthFt: 7.71, pieces: { '250': 1, '260': 2 } }, // 2350mm, t_pcs=3
        { lengthFt: 8.038, pieces: { '110': 1, '160': 1, '280': 1 } }, // 2450mm, t_pcs=3
        { lengthFt: 8.202, pieces: { '100': 1, '180': 1 } }, // 2500mm, t_pcs=2
        { lengthFt: 8.366, pieces: { '130': 1, '190': 1, '200': 1 } }, // 2550mm, t_pcs=3
      ],
    },
    totals: { pieces: 47, boardFeet: null, volumeM3: 1.074 },
  },
  {
    bundleNo: "14-C",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [60, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 260, 270, 280, 300, 340],
      rows: [
        { lengthFt: 7.054, pieces: { '60': 1, '100': 4, '110': 3, '130': 5, '150': 1, '160': 1, '170': 1, '200': 1, '210': 1, '220': 1, '230': 1, '260': 1, '300': 1, '340': 1 } }, // 2150mm, t_pcs=23
        { lengthFt: 7.218, pieces: { '60': 1, '90': 1, '120': 1, '130': 2, '160': 2 } }, // 2200mm, t_pcs=7
        { lengthFt: 7.382, pieces: { '100': 1, '150': 1, '170': 1, '190': 1, '210': 2, '220': 1, '260': 1 } }, // 2250mm, t_pcs=8
        { lengthFt: 7.546, pieces: { '80': 1, '110': 2, '120': 1, '130': 1, '150': 2, '160': 1, '180': 1, '190': 1, '210': 1, '220': 1, '260': 1, '280': 1 } }, // 2300mm, t_pcs=14
        { lengthFt: 7.71, pieces: { '110': 1, '140': 1, '160': 1, '190': 1 } }, // 2350mm, t_pcs=4
        { lengthFt: 7.874, pieces: { '160': 1, '180': 1, '190': 1, '200': 1, '210': 1, '230': 1 } }, // 2400mm, t_pcs=6
        { lengthFt: 8.038, pieces: { '140': 1, '180': 1, '220': 1, '230': 1, '270': 1 } }, // 2450mm, t_pcs=5
      ],
    },
    totals: { pieces: 67, boardFeet: null, volumeM3: 1.2687 },
  },
  {
    bundleNo: "15-B",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 220, 240, 250, 260, 270, 280, 290, 300, 320, 370, 390, 400],
      rows: [
        { lengthFt: 6.89, pieces: { '80': 1, '100': 1, '120': 1, '150': 1, '170': 1, '250': 1, '370': 1 } }, // 2100mm, t_pcs=7
        { lengthFt: 7.054, pieces: { '80': 1, '150': 1 } }, // 2150mm, t_pcs=2
        { lengthFt: 7.218, pieces: { '120': 1, '190': 1, '200': 1, '220': 1, '240': 1, '270': 1 } }, // 2200mm, t_pcs=6
        { lengthFt: 7.546, pieces: { '90': 2, '100': 3, '130': 3, '160': 1 } }, // 2300mm, t_pcs=9
        { lengthFt: 7.71, pieces: { '150': 1 } }, // 2350mm, t_pcs=1
        { lengthFt: 7.874, pieces: { '70': 1, '150': 1, '160': 1, '240': 1, '250': 1 } }, // 2400mm, t_pcs=5
        { lengthFt: 8.038, pieces: { '70': 1, '90': 1, '100': 8, '110': 3, '120': 2, '130': 3, '140': 7, '150': 3, '160': 2, '170': 8, '180': 6, '190': 2, '200': 3, '220': 4, '240': 1, '260': 1, '320': 1 } }, // 2450mm, t_pcs=56
        { lengthFt: 8.202, pieces: { '100': 1, '110': 1, '130': 2, '160': 3, '170': 1, '190': 1, '220': 2, '240': 1, '260': 2, '280': 1, '290': 1, '300': 1, '370': 1, '390': 1, '400': 1 } }, // 2500mm, t_pcs=20
        { lengthFt: 8.53, pieces: { '110': 1, '220': 1 } }, // 2600mm, t_pcs=2
      ],
    },
    totals: { pieces: 108, boardFeet: null, volumeM3: 2.221 },
  },
  {
    bundleNo: "16-B",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [60, 70, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 270, 280, 300, 330, 370, 390, 400, 410, 420],
      rows: [
        { lengthFt: 6.89, pieces: { '220': 1, '250': 1, '270': 1 } }, // 2100mm, t_pcs=3
        { lengthFt: 7.054, pieces: { '90': 1, '100': 2, '140': 1, '200': 1, '210': 1, '400': 1 } }, // 2150mm, t_pcs=7
        { lengthFt: 7.218, pieces: { '90': 1, '100': 1, '120': 1, '220': 1, '250': 1 } }, // 2200mm, t_pcs=5
        { lengthFt: 7.546, pieces: { '130': 1, '150': 1, '180': 1, '230': 2 } }, // 2300mm, t_pcs=5
        { lengthFt: 7.71, pieces: { '90': 1, '100': 1, '110': 1, '120': 2, '130': 1, '140': 2, '210': 1, '270': 1 } }, // 2350mm, t_pcs=10
        { lengthFt: 8.038, pieces: { '110': 1, '120': 1, '130': 2, '160': 1 } }, // 2450mm, t_pcs=5
        { lengthFt: 8.202, pieces: { '100': 1, '140': 1, '150': 1, '160': 1, '170': 1, '200': 1, '210': 2, '250': 1 } }, // 2500mm, t_pcs=9
        { lengthFt: 8.366, pieces: { '60': 1, '90': 2, '100': 4, '110': 2, '120': 2, '130': 1, '140': 1, '150': 1, '160': 1, '180': 2, '190': 2, '200': 1, '210': 1, '220': 2, '230': 4, '240': 2, '280': 1, '370': 1, '390': 2, '410': 1 } }, // 2550mm, t_pcs=34
        { lengthFt: 8.53, pieces: { '170': 1, '190': 2, '300': 1 } }, // 2600mm, t_pcs=4
        { lengthFt: 8.694, pieces: { '70': 1, '150': 2, '230': 1, '270': 1, '330': 1, '410': 1, '420': 1 } }, // 2650mm, t_pcs=8
        { lengthFt: 8.858, pieces: { '100': 1, '120': 1, '140': 1, '160': 1, '200': 1 } }, // 2700mm, t_pcs=5
        { lengthFt: 9.35, pieces: { '160': 1 } }, // 2850mm, t_pcs=1
      ],
    },
    totals: { pieces: 96, boardFeet: null, volumeM3: 2.1799 },
  },
  {
    bundleNo: "5",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 9.186,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 310],
      rows: [
        { lengthFt: 9.186, pieces: { '100': 1, '120': 1, '130': 2, '140': 7, '150': 3, '160': 4, '170': 11, '180': 3, '190': 3, '200': 10, '210': 3, '220': 7, '230': 10, '240': 8, '250': 3, '260': 11, '270': 8, '280': 4, '310': 1 } }, // 2800mm, t_pcs=100
      ],
    },
    totals: { pieces: 100, boardFeet: null, volumeM3: 2.9568 },
  },
  {
    bundleNo: "6",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.53,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280],
      rows: [
        { lengthFt: 8.53, pieces: { '90': 1, '100': 1, '110': 3, '120': 1, '130': 2, '140': 5, '150': 7, '160': 5, '170': 6, '180': 8, '190': 6, '200': 1, '210': 10, '220': 6, '230': 5, '240': 10, '250': 8, '260': 6, '270': 7, '280': 3 } }, // 2600mm, t_pcs=101
      ],
    },
    totals: { pieces: 101, boardFeet: null, volumeM3: 2.6663 },
  },
  {
    bundleNo: "7",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.53,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [80, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270],
      rows: [
        { lengthFt: 8.53, pieces: { '80': 1, '110': 3, '120': 1, '130': 8, '140': 11, '150': 6, '160': 3, '170': 5, '180': 5, '190': 6, '200': 4, '210': 4, '220': 6, '230': 7, '240': 13, '250': 14, '260': 3, '270': 1 } }, // 2600mm, t_pcs=101
      ],
    },
    totals: { pieces: 101, boardFeet: null, volumeM3: 2.5506 },
  },
  {
    bundleNo: "8",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: 8.53,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [110, 120, 130, 140, 150, 160, 170, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280],
      rows: [
        { lengthFt: 8.53, pieces: { '110': 1, '120': 4, '130': 2, '140': 7, '150': 8, '160': 3, '170': 3, '190': 5, '200': 5, '210': 7, '220': 8, '230': 15, '240': 12, '250': 10, '260': 5, '270': 5, '280': 2 } }, // 2600mm, t_pcs=102
      ],
    },
    totals: { pieces: 102, boardFeet: null, volumeM3: 2.7612 },
  },
  {
    bundleNo: "9",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 210, 220, 230, 240, 250, 260, 270, 280, 290],
      rows: [
        { lengthFt: 7.874, pieces: { '90': 1, '100': 1, '110': 1, '130': 1, '140': 2, '150': 3, '160': 3, '170': 1, '180': 2, '210': 3, '220': 3, '230': 4, '240': 5, '250': 3, '260': 4, '270': 2, '290': 1 } }, // 2400mm, t_pcs=40
        { lengthFt: 8.53, pieces: { '100': 1, '110': 3, '120': 4, '130': 9, '140': 4, '150': 8, '160': 9, '170': 2, '180': 7, '190': 3, '210': 6, '220': 5, '230': 3, '240': 3, '260': 1, '270': 1, '280': 1 } }, // 2600mm, t_pcs=70
      ],
    },
    totals: { pieces: 110, boardFeet: null, volumeM3: 2.5479 },
  },
  {
    bundleNo: "12-A",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 110, 120, 130, 140, 150, 160, 170, 180, 200, 210, 220, 230, 250, 260, 270, 280, 300],
      rows: [
        { lengthFt: 5.906, pieces: { '270': 1 } }, // 1800mm, t_pcs=1
        { lengthFt: 6.07, pieces: { '130': 1, '140': 1, '160': 1, '210': 1, '220': 1, '230': 1, '250': 2, '280': 1 } }, // 1850mm, t_pcs=9
        { lengthFt: 6.234, pieces: { '100': 1, '120': 1, '170': 1, '180': 1, '220': 2, '260': 3 } }, // 1900mm, t_pcs=9
        { lengthFt: 6.398, pieces: { '110': 1, '130': 1, '140': 1, '180': 1, '200': 1, '230': 1, '250': 1, '280': 1 } }, // 1950mm, t_pcs=8
        { lengthFt: 6.562, pieces: { '120': 1, '150': 1, '200': 1, '220': 1, '270': 1, '300': 1 } }, // 2000mm, t_pcs=6
        { lengthFt: 6.726, pieces: { '150': 1, '230': 1, '300': 1 } }, // 2050mm, t_pcs=3
      ],
    },
    totals: { pieces: 36, boardFeet: null, volumeM3: 0.7116 },
  },
  {
    bundleNo: "13-A",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [130, 140, 150, 160, 180, 210, 220, 230, 240, 250, 270, 280, 290],
      rows: [
        { lengthFt: 2.789, pieces: { '230': 1 } }, // 850mm, t_pcs=1
        { lengthFt: 2.953, pieces: { '250': 1 } }, // 900mm, t_pcs=1
        { lengthFt: 3.281, pieces: { '220': 1 } }, // 1000mm, t_pcs=1
        { lengthFt: 3.609, pieces: { '230': 1 } }, // 1100mm, t_pcs=1
        { lengthFt: 3.937, pieces: { '140': 1 } }, // 1200mm, t_pcs=1
        { lengthFt: 4.265, pieces: { '210': 1 } }, // 1300mm, t_pcs=1
        { lengthFt: 4.429, pieces: { '220': 2 } }, // 1350mm, t_pcs=2
        { lengthFt: 5.906, pieces: { '130': 2, '150': 1, '160': 1, '210': 1, '220': 1, '230': 1, '240': 2, '270': 1, '280': 1 } }, // 1800mm, t_pcs=11
        { lengthFt: 6.234, pieces: { '130': 1, '180': 1, '220': 1, '230': 1, '250': 1 } }, // 1900mm, t_pcs=5
        { lengthFt: 6.398, pieces: { '140': 2, '150': 1, '160': 1, '180': 1, '220': 1, '230': 1, '270': 1 } }, // 1950mm, t_pcs=8
        { lengthFt: 6.562, pieces: { '140': 1, '150': 1, '240': 1, '290': 1 } }, // 2000mm, t_pcs=4
      ],
    },
    totals: { pieces: 36, boardFeet: null, volumeM3: 0.6235 },
  },
  {
    bundleNo: "14-A",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [100, 110, 120, 130, 140, 150, 160, 180, 190, 200, 210, 220, 230, 240, 250, 260, 280],
      rows: [
        { lengthFt: 2.953, pieces: { '110': 1, '120': 1, '150': 3, '210': 1, '250': 1, '260': 1 } }, // 900mm, t_pcs=8
        { lengthFt: 3.117, pieces: { '100': 1, '110': 1, '120': 2, '130': 1, '140': 1, '180': 1, '210': 1, '220': 2, '260': 1 } }, // 950mm, t_pcs=11
        { lengthFt: 3.281, pieces: { '110': 1, '120': 1, '130': 2, '180': 1, '230': 1, '240': 2 } }, // 1000mm, t_pcs=8
        { lengthFt: 3.445, pieces: { '100': 1, '130': 1, '200': 1 } }, // 1050mm, t_pcs=3
        { lengthFt: 3.609, pieces: { '110': 1, '140': 1 } }, // 1100mm, t_pcs=2
        { lengthFt: 3.773, pieces: { '120': 1, '130': 2, '150': 1, '200': 1, '220': 1, '250': 1 } }, // 1150mm, t_pcs=7
        { lengthFt: 3.937, pieces: { '140': 1, '230': 1 } }, // 1200mm, t_pcs=2
        { lengthFt: 4.101, pieces: { '150': 1, '210': 1, '240': 1 } }, // 1250mm, t_pcs=3
        { lengthFt: 4.265, pieces: { '120': 1, '140': 1, '150': 1, '230': 1 } }, // 1300mm, t_pcs=4
        { lengthFt: 4.429, pieces: { '110': 1, '150': 1, '190': 1 } }, // 1350mm, t_pcs=3
        { lengthFt: 4.593, pieces: { '130': 1, '160': 1, '210': 1, '220': 1, '240': 1, '260': 1 } }, // 1400mm, t_pcs=6
        { lengthFt: 4.757, pieces: { '110': 1, '120': 1, '160': 1, '180': 1, '230': 2, '250': 1 } }, // 1450mm, t_pcs=7
        { lengthFt: 4.921, pieces: { '120': 4, '150': 2, '200': 1, '220': 1, '240': 3 } }, // 1500mm, t_pcs=11
        { lengthFt: 5.085, pieces: { '130': 1, '140': 2, '210': 2 } }, // 1550mm, t_pcs=5
        { lengthFt: 5.577, pieces: { '100': 2, '110': 1, '130': 2, '160': 2, '180': 1, '220': 1, '240': 2, '260': 1 } }, // 1700mm, t_pcs=12
        { lengthFt: 5.741, pieces: { '120': 1, '210': 1, '220': 1, '240': 1, '250': 1, '280': 1 } }, // 1750mm, t_pcs=6
        { lengthFt: 5.906, pieces: { '120': 1, '130': 2, '140': 1, '160': 1, '200': 1, '240': 2, '280': 1 } }, // 1800mm, t_pcs=9
        { lengthFt: 6.07, pieces: { '100': 1, '160': 1, '190': 1, '210': 1 } }, // 1850mm, t_pcs=4
      ],
    },
    totals: { pieces: 111, boardFeet: null, volumeM3: 1.3395 },
  },
  {
    bundleNo: "14-B",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 250, 260, 270],
      rows: [
        { lengthFt: 5.085, pieces: { '260': 1 } }, // 1550mm, t_pcs=1
        { lengthFt: 5.249, pieces: { '100': 1, '120': 1, '200': 1 } }, // 1600mm, t_pcs=3
        { lengthFt: 5.413, pieces: { '120': 1, '140': 1 } }, // 1650mm, t_pcs=2
        { lengthFt: 5.577, pieces: { '80': 1, '90': 1, '110': 1, '150': 2, '160': 1, '200': 3, '260': 1 } }, // 1700mm, t_pcs=10
        { lengthFt: 5.741, pieces: { '80': 1, '130': 1, '150': 1, '190': 1 } }, // 1750mm, t_pcs=4
        { lengthFt: 5.906, pieces: { '120': 1, '130': 1, '150': 1 } }, // 1800mm, t_pcs=3
        { lengthFt: 6.234, pieces: { '80': 1, '100': 1, '160': 1, '250': 1, '270': 1 } }, // 1900mm, t_pcs=5
        { lengthFt: 6.398, pieces: { '80': 1, '110': 2, '120': 5, '130': 2, '140': 1, '150': 3, '170': 1, '180': 1, '200': 1, '210': 1, '220': 1 } }, // 1950mm, t_pcs=19
        { lengthFt: 6.562, pieces: { '110': 1, '120': 1, '150': 1 } }, // 2000mm, t_pcs=3
        { lengthFt: 6.726, pieces: { '90': 2, '120': 1, '130': 1, '150': 1, '170': 1, '190': 1 } }, // 2050mm, t_pcs=7
      ],
    },
    totals: { pieces: 57, boardFeet: null, volumeM3: 0.778 },
  },
  {
    bundleNo: "15-A",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [80, 100, 120, 150, 160, 210],
      rows: [
        { lengthFt: 5.906, pieces: { '100': 1, '150': 1 } }, // 1800mm, t_pcs=2
        { lengthFt: 6.07, pieces: { '80': 1, '100': 1, '150': 1 } }, // 1850mm, t_pcs=3
        { lengthFt: 6.562, pieces: { '160': 1 } }, // 2000mm, t_pcs=1
        { lengthFt: 6.726, pieces: { '120': 1, '210': 1 } }, // 2050mm, t_pcs=2
      ],
    },
    totals: { pieces: 8, boardFeet: null, volumeM3: 0.1029 },
  },
  {
    bundleNo: "16-A",
    lot: null,
    species: "ZEBRANO 70-80% QS KD",
    grade: "FIRST AND SECOND",
    thickness: { raw: "50.00mm", inches: 1.969 },
    width: null,
    widthPolicy: 'printed',
    lengthFt: null,
    matrix: {
      widthUnit: 'mm',
      widthsIn: [70, 120, 150, 170, 200, 240, 270, 310, 350],
      rows: [
        { lengthFt: 6.398, pieces: { '70': 1 } }, // 1950mm, t_pcs=1
        { lengthFt: 6.562, pieces: { '150': 1, '170': 1, '200': 1, '310': 1, '350': 1 } }, // 2000mm, t_pcs=5
        { lengthFt: 6.726, pieces: { '120': 1, '240': 1, '270': 1 } }, // 2050mm, t_pcs=3
      ],
    },
    totals: { pieces: 9, boardFeet: null, volumeM3: 0.1894 },
  },
  ],
  provenance: {
    sourceFile: "pl inv 01368.xlsx",
    parsedAt: null,
    skill: 'gen-zebrano.mjs@1 (SheetJS read, reconciled)',
    reviewedBy: null,
  },
};

/** The document's own figures, for tests to assert against. */
export const TALLY_ZEBRANO_TOTALS = { bundles: 18, pieces: 1351, multiLengthBundles: 13 } as const;
